# Generated by Django 5.2.4 on 2025-07-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='classe',
            new_name='departement',
        ),
    ]
